name: nor_genes
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - sickle-trim=1.33
  - bwa=0.7.17
  - fastqc=0.11.9
  - samtools=1.3.1
  - biopython=1.76
  - sra-tools=2.9.1
  - subread=2.0.1
  - r-base=3.5.1
  - r-purrr=0.3.4
  - r-dplyr=0.8.5
  - r-here
